name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          git \
          libstdc++6 \
          python3-pip \
          zip \
          unzip \
          openjdk-11-jdk
        pip install --upgrade pip
        pip install cython buildozer

    - name: Accept Android SDK licenses
      run: |
        mkdir -p $HOME/.android
        echo '### User Agreements accepted by GitHub Actions' > $HOME/.android/repositories.cfg
        yes | buildozer android debug || true  # اجرای اولیه برای دانلود SDK
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dongyar-apk
        path: bin/*.apk
